### ISSUE TITLE
попробуйте запустить на большом файле

### ISSUE THREAD

**Issue by egor1989** [AlexSmith1991/baltinfocom-test#1]
https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

**Comment by AlexSmith1991** [comment]
Егор, добрый день!

Прошу прощения за долгий ответ, на работе завал небольшой неожиданно
организовался. Попытался запустить - выдал ошибку что кончилось место для
кучи, быстро решить ее не получилось. Можно попробовать программу додумать
для возможности обработки больших объемов или задание уже провалено?

Спасибо!

чт, 21 апр. 2022 г. в 12:36, Egor Ivanov ***@***.***>:

**Comment by egor1989** [comment]
Да, доделайте до понедельника

**Comment by AlexSmith1991** [comment]
Егор, добрый день!

К сожалению так и не получилось придумать как изменить программу чтобы она
могла обработать большой файл. Спасибо за интересную задачу и возможность
испытать свои силы! Если возможно, подскажите, пожалуйста, там решение
предполагалось с использованием исключительно Java Core, или надо было
использовать какие-то специальные библиотеки или вспомогательную БД?

Спасибо!

пт, 22 апр. 2022 г. в 18:11, Egor Ivanov ***@***.***>:

**Comment by egor1989** [comment]
например вот так
https://github.com/WearierPuma01/testWork
